# docker compose run --rm widoco
services:
  widoco:
    image: ghcr.io/dgarijo/widoco:v1.4.25
    platform: linux/amd64
    stdin_open: true    
    tty: true           
    volumes:
      - ./:/usr/local/widoco/in:Z
      - ../docs/v1.3:/usr/local/widoco/out:Z
    command: -ontFile in/acdd.ttl -outFolder out -rewriteAll -getOntologyMetadata
